// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/croppedSlider.png"
    | "/icon/mascot.png"
    | "/icon/slider.png"
    | "/popup.html"
    | "/sprites/celebration_sprite_sheet.png"
    | "/sprites/drying_sprite_sheet.png"
    | "/sprites/dying_spritesheet.png"
    | "/sprites/happy_idle_sheet.png"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
